#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse
import logging
import requests
import sys

logger = logging.getLogger(__name__)


def get_parser():
    """ Return argument parser. """
    parser = argparse.ArgumentParser(
        description=""
    )
    parser.add_argument('user')
    parser.add_argument('password')
    parser.add_argument('url')
    return parser


def command(user, password, url):
    """ Do something spectacular. """
    from pprint import pprint
    auth = user, password
    # workspace
    workspace = requests.get(url, auth=auth).json()
    # coverage stores
    coverage_store_dict = workspace['workspace']
    del coverage_store_dict['name']
    coverage_store_urls = coverage_store_dict.values()
    coverage_stores = [requests.get(u, auth=auth).json()
                       for u in coverage_store_urls]
    # data stores
    for coverage_store in coverage_stores:
        for data_store in coverage_store.values():
            if not isinstance(data_store, dict):
                continue
            for something in data_store.values():
                for feature_type in something:
                    print(feature_type['name'])


def main():
    """ Call command with args from parser. """
    logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
    command(**vars(get_parser().parse_args()))


if __name__ == '__main__':
    exit(main())
