#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function
from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import division

from matplotlib import colors
from matplotlib import cm

import numpy as np
import sys

TEMPLATE = '<ColorMapEntry color="{}" quantity="{}"/>\n'
FLAT = 181


def main():
    quantity = np.linspace(-10, 10, 101)
    normalize = colors.Normalize()
    colormap = cm.gist_earth
    color = map(colors.rgb2hex, colormap(normalize(quantity)))
    lines = [16 * ' ' + TEMPLATE.format(*t)
             for t in zip(color, quantity)]

    sys.stdout.write(''.join(lines))


if __name__ == '__main__':
    exit(main())
