#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function
from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import division

import sys

from xml.etree import ElementTree
from matplotlib import colors

TEMPLATE = '    {},\n'


def main():
    colordict = {}
    tree = ElementTree.parse(sys.argv[1])
    for element in tree.iter():
        if element.tag.endswith('ColorMapEntry'):
            color = colors.hex2color(element.attrib['color'])
            value = int(float(element.attrib['quantity']))
            colordict[value] = color
    #print(max(colordict.keys()))
    for i in range(max(colordict.keys()) + 1):
        if i in colordict:
            sys.stdout.write(TEMPLATE.format(colordict[i] + (1,)))
        else:
            sys.stdout.write(TEMPLATE.format((0, 0, 0, 0)))


if __name__ == '__main__':
    exit(main())
