#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function
from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import division

import gdal
import sys


def main():
    dataset = gdal.Open(sys.argv[1])
    array = dataset.ReadAsArray()
    print(array.max())


if __name__ == '__main__':
    exit(main())
