#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function
from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import division

import gdal
import sys


def main():
    dataset = gdal.Open(sys.argv[1])
    width, height = dataset.RasterXSize, dataset.RasterYSize
    geotransform = dataset.GetGeoTransform()
    bbox = ','.join(map(str, [
        geotransform[0],
        geotransform[3] + height * geotransform[5],
        geotransform[0] + width * geotransform[1],
        geotransform[3],
    ]))
    sys.stdout.write(bbox)


if __name__ == '__main__':
    exit(main())
