#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function
from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import division

import argparse
import csv
import datetime
import logging
import sys

logger = logging.getLogger(__name__)


def get_parser():
    """ Return argument parser. """
    parser = argparse.ArgumentParser(
        description=""
    )
    # Add arguments here.
    return parser


def command():
    """
    Example
    -------
    Subject,Start Date,Start Time,End Date,End Time,All Day
    Event,Description,Location,Private
    Final Exam,05/12/08,07:10:00 PM,05/12/08,10:00:00 PM,False,Two
    essay questions that will cover topics covered throughout the
    semester,"Columbia, Schermerhorn 614",True
    """

    reader = csv.DictReader(sys.stdin)
    writer = csv.DictWriter(sys.stdout, fieldnames=[
        'Subject',
        'Start Date',
        'Start Time',
        'End Date',
        'End Time',
        'All Day Event',
        'Description',
        'Location',
        'Private',
    ])
    writer.writeheader()

    # Here it all happens
    for record in reader:
        datestring = record['date']

        dt1 = datetime.datetime.strptime(datestring,
                                         '%d-%m-%Y').replace(hour=20)
        dt2 = datetime.datetime.strptime(datestring,
                                         '%d-%m-%Y').replace(hour=22)

        # Base data
        result = {
            'Start Date': dt1.strftime('%d/%m/%Y'),
            'Start Time': dt1.strftime('%I:%M:%S %p'),
            'End Date': dt2.strftime('%d/%m/%Y'),
            'End Time': dt2.strftime('%I:%M:%S %p'),
        }

        # Specific data
        result.update(Subject=record['subject'])

        writer.writerow(result)


def main():
    """ Call command with args from parser. """
    logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
    command(**vars(get_parser().parse_args()))


if __name__ == '__main__':
    exit(main())
